### ISSUE TITLE
max() arg is an empty sequence error when using Greengenes reference

### ISSUE THREAD

**Issue by aboffin** [qunfengdong/BLCA#10]
Hi,
When I run BLCA as follows:
```
python 2.blca_main.py -i ungap_Ano.fasta -r gg/gg_13_5_taxonomy.taxonomy \
  -o gg_ungap_Ano.blca.out
```
I get the following error:
```
blastdbcmd is located in your PATH!
muscle is located in your PATH!
>  > Fasta file read in!!
>  > Reading in taxonomy information! ....
blastn is located in your PATH!
> > Running blast!!
> > Blastn Finished!!
>  > Read in blast output!
Traceback (most recent call last):
  File "2.blca_main.py", line 355, in <module>
    outout.write(le+":"+max(lexsum,key=lexsum.get)+";"+str(max(lexsum.values()))+";")
ValueError: max() arg is an empty sequence
```

However, when I use the NCBI 16S rRNA database, there is no error and the output file is generated. Any pointers are appreciated.

Thanks in advance,

**Comment by yingeddi2008** [comment]
Hi Senthil,

Thanks for using our software!

I just did a test run of greengene database using the test.fasta, and it
successfully finished the job. No error message popped up.

Also I noticed in your code that you didn't provide the -q --db argument,
that might be where the issue is coming from. Because the default database
is NCBI's 16s, while the taxonomy file is greengene, so the program won't
be able to find the matching taxonomy information. Can you try adding the
-q --db argument and run the program again?

If the error message persists, can you provide me with the input file? I
will try to produce the same error message.

Thanks,

Eddi

**Comment by aboffin** [comment]
Hi,

Thank you for looking into this issue. I get the same error if I run the command with "-q" option (which really shouldn't matter since it defaults to "db/16SMicrobial"). 

Here is the error message after running the command:

```
python 2.blca_main.py -i ungap_Anoxy.fasta -r gg/gg_13_5_taxonomy.taxonomy   -o gg_ungap_Ano.blca.out -q db/16SMicrobial 
blastdbcmd is located in your PATH!
muscle is located in your PATH!
>  > Fasta file read in!!
>  > Reading in taxonomy information! ....
blastn is located in your PATH!
> > Running blast!!
> > Blastn Finished!!
>  > Read in blast output!
Traceback (most recent call last):
  File "2.blca_main.py", line 355, in <module>
    outout.write(le+":"+max(lexsum,key=lexsum.get)+";"+str(max(lexsum.values()))+";")
ValueError: max() arg is an empty sequence
```

Here is the first 5 sequences of the FASTA file (uncap_Anoxy.fasta):
```
>Otu00001
TACGGAGGGCGCGAGCGTTACCCGGATTTACTGGGCGTAAAGGGCGTGTAGGCGGCTTGGGGCGTCCCATGTGAAAGGCCACGGCTCAACCGTGGAGGAGCGTGGGATACGCTCAGGCTAGACGGTGGGAGAGGGTGGTGGAATTCCCGGAGTAGCGGTGAAATGCGCAGATACCGGGAGGAACGCCGATGGCGAAGGCAGCCACCTGGCCCACATGTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACCGG
>Otu00002
GACGGGGGATGCAAGCGTTATCCGGAATCACTGGGCGTAAAGCGTCTGTAGGTGGTGATGCAAGTCACTGGTGCAAAACTCTGGCTCAACCGGAGGAAAGCCAGTGAAACTGCATGACTAGAGTGTGGGAGAGGTAGAAGGAATTCCCTGAGTAGCGGTGAAATGCGTAGATACAGGGAAGAACACCGGAGGCGAAAGCGTTCTACTGGAACACAACTGACACTGAGAGACGAAAGCTAGGGGAGCGAATGGG
>Otu00003
GACAGAGGGGGCGAGCGTTGTCCGGAGTCACTGGGCGTAAAGCGCGCGCAGGCGGCAACCTAAGTGTCGTGTGAAAGCCCCCGGCTCAACCGGGGGAGGCCATGGCAAACTGGGTCGCTCGAGCTGCGGAGAGGCCCCTCGAATTGCCGGTGTAGCGGTGAAATGCGTAGAGATCGGCAGGAAGACCAAGGGGGAAGCCAGGGGGCTGGCCGCAGGCTGACGCTGAGGCGCGACAGCGTGGGGAGCAAACCGG
>Otu00004
TACGTAGGGGGCGAGCGTTGCCCGAATTTACTGGGCGTAAAGCGCACGTAGGCGGCTTCGTAAGTCTGGTGTGAAATCTCACGGCTCAACCGAGAGGCTGCACCAGATACTGCGAAGCTCGAGGACGGGAGAGGAGATTGGAATTCCCGGTGTAGCGGTGAAATGCATTGATATCGGGAGGAACACCAGTGGCGAAGGCGGATCTCTGGCCCGTTGCTGACGCTGAGGTGCGAAAGCTGGGGGAGCGAAAGGG
>Otu00005
GACAGAGGGGGCAAGCGTTGTCCGGAGTTACTGGGCGTAAAGGGCGCGGAGGCGGTCTGCGGCGTCGGCGCTGAAAGCGCCCCGCTTAACGGGGCGAGGCGTGCCGATACGCGCAGACTTGAGGCGAGCAGAGGGTGGTGGAATTCCGGGTGGAGCGGTGAAATGCGTAGAGATCCGGAGGAACGCCAGTGGGGAAGCCGGCCACCTGGGCTCGTCCTGACGCTGCGGCGCGACAGCGTGGGGAGCAAACCGG
```

which when used in place of the original file, also gave the same error.

Thank you,
Senthil
